
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-9am-3
owner: ucsb-cs156-m23
repo_name: team03-m23-9am-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyODI4OTQ1","is_bot":false,"login":"LolExile","name":"Johnny Wang "},"headRefName":"Johnny-HelpRequestFin","number":69,"title":"Johnny help request fin","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/69"},{"author":{"id":"U_kgDOBXuuuQ","is_bot":false,"login":"Danny-You","name":""},"headRefName":"Danny-Articles-table","number":68,"title":"Added Articles Table ","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/68"},{"author":{"id":"MDQ6VXNlcjYyMzY5NTUy","is_bot":false,"login":"InariHimeko","name":""},"headRefName":"Wenxuan-RecRequest-Pages","number":67,"title":"Wenxuan's PR of all except test","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/67"},{"author":{"id":"MDQ6VXNlcjcyODI4OTQ1","is_bot":false,"login":"LolExile","name":"Johnny Wang "},"headRefName":"Johnny-helpRequestFixtures","number":66,"title":"Johnny help request fixtures","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/66"},{"author":{"id":"U_kgDOBXuuuQ","is_bot":false,"login":"Danny-You","name":""},"headRefName":"Danny-Articles-form","number":65,"title":"Added Articles form and tests","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/65"},{"author":{"id":"U_kgDOBXuuuQ","is_bot":false,"login":"Danny-You","name":""},"headRefName":"Danny-Articles-fixtures","number":62,"title":"Added Articles fixture file","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/62"},{"author":{"id":"U_kgDOBXuuuQ","is_bot":false,"login":"Danny-You","name":""},"headRefName":"Danny-Articles-team02files","number":61,"title":"DY - Added team02 files","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/61"}]
