
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-9am-3
owner: ucsb-cs156-m23
repo_name: team03-m23-9am-3
pull_requests: [{"author":{"id":"U_kgDOBtnu_g","is_bot":false,"login":"Kanagawa-okiNamiUra","name":""},"headRefName":"Albert-UCSBMenuItem_Frontend","number":60,"title":"AW--Completed All Frontend Requirements for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/60"},{"author":{"id":"U_kgDOBtnu_g","is_bot":false,"login":"Kanagawa-okiNamiUra","name":""},"headRefName":"Albert-UCSBMenuItem_CRUDCopy","number":59,"title":"AW-copied UCSBMenuItems Backend files from team02","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/59"},{"author":{"id":"U_kgDOBXznew","is_bot":false,"login":"lawrencewang30","name":""},"headRefName":"Lawrence-UCSBOrganization-table","number":58,"title":"added UCSBOrganization table","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/58"},{"author":{"id":"U_kgDOBXznew","is_bot":false,"login":"lawrencewang30","name":""},"headRefName":"Lawrence-UCSBOrganization-form","number":57,"title":"Added UCSB Organization form and tests","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/57"},{"author":{"id":"U_kgDOBXznew","is_bot":false,"login":"lawrencewang30","name":""},"headRefName":"Lawrence-UCSBOrganization-fixtures","number":56,"title":"Added UCSBOrganization fixture file","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/56"},{"author":{"id":"U_kgDOBXznew","is_bot":false,"login":"lawrencewang30","name":""},"headRefName":"Lawrence-UCSBOrganization-team02files","number":55,"title":"LW - Added team02 files","url":"https://github.com/ucsb-cs156-m23/team03-m23-9am-3/pull/55"}]
